### ISSUE TITLE
Application fails to start due to missing [D1_ACCOUNT_ID] environment variable

### ISSUE THREAD

**Issue by tiger360** [kdhrubo/db2rest#347]
## Issue Description

The `db2rest` application fails to start due to an unresolved placeholder for the `D1_ACCOUNT_ID` environment variable. When running the following command:

docker run -e DB_URL=jdbc:mysql://zeus-mysql:3306/ZeusEdu -e DB_USER=rooot -e DB_PASSWORD=147258369 kdhrubo/db2rest:latest

The application throws the following error:

<details><summary>Details</summary>
<p>

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.2)

2024-03-13T12:31:13.213Z  INFO 1 --- [           main] com.homihq.db2rest.Db2restApplication    : Starting Db2restApplication v0.2.0-RC1 using Java 21.0.2 with PID 1 (/opt/app/db2rest.jar started by root in /opt/app)
2024-03-13T12:31:13.215Z  INFO 1 --- [           main] com.homihq.db2rest.Db2restApplication    : No active profile set, falling back to 1 default profile: "default"
2024-03-13T12:31:15.152Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-03-13T12:31:15.165Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-13T12:31:15.165Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-13T12:31:15.208Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-13T12:31:15.210Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1900 ms
2024-03-13T12:31:15.442Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'd1OperationService' defined in URL [jar:nested:/opt/app/db2rest.jar/!BOOT-INF/classes/!/com/homihq/db2rest/dbop/D1OperationService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'd1Configuration': Injection of autowired dependencies failed
2024-03-13T12:31:15.447Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-03-13T12:31:15.670Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-13T12:31:15.706Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'd1OperationService' defined in URL [jar:nested:/opt/app/db2rest.jar/!BOOT-INF/classes/!/com/homihq/db2rest/dbop/D1OperationService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'd1Configuration': Injection of autowired dependencies failed
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.3.jar!/:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar!/:6.1.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at com.homihq.db2rest.Db2restApplication.main(Db2restApplication.java:11) ~[!/:0.2.0-RC1]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[db2rest.jar:0.2.0-RC1]
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[db2rest.jar:0.2.0-RC1]
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[db2rest.jar:0.2.0-RC1]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'd1Configuration': Injection of autowired dependencies failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:514) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1418) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785) ~[spring-beans-6.1.3.jar!/:6.1.3]
	... 24 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'D1_ACCOUNT_ID' in value "${D1_ACCOUNT_ID}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:230) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:79) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:60) ~[spring-boot-3.2.2.jar!/:3.2.2]
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:552) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:153) ~[spring-context-6.1.3.jar!/:6.1.3]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:149) ~[spring-context-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.PropertySourcesPropertyResolver.getPropertyAsRawString(PropertySourcesPropertyResolver.java:74) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:153) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-6.1.3.jar!/:6.1.3]
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:200) ~[spring-context-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:921) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1374) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:784) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:767) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145) ~[spring-beans-6.1.3.jar!/:6.1.3]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:508) ~[spring-beans-6.1.3.jar!/:6.1.3]
	... 45 common frames omitted

</p>
</details> 

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'D1_ACCOUNT_ID' in value "${D1_ACCOUNT_ID}"
at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180) ~[spring-core-6.1.3.jar!/:6.1.3]
... (stacktrace omitted)

## Expected Behavior

The application should start successfully and run without any issues.

## Actual Behavior

The application fails to start due to the unresolved `D1_ACCOUNT_ID` placeholder, which seems to be related to a missing environment variable.

## Environment

- Application version: db2rest v0.2.0-RC1
- Docker version: Docker version 25.0.4, build 1a576c5
- Operating System: Popos

## Reproducible Steps

1. Pull the `kdhrubo/db2rest:latest` Docker image.
2. Run the Docker container with the provided command:
docker run -e DB_URL=jdbc:mysql://zeus-mysql:3306/ZeusEdu -e DB_USER=root2 -e DB_PASSWORD=123456 kdhrubo/db2rest:latest

3. Observe the application failing to start with the error related to the unresolved `D1_ACCOUNT_ID` placeholder.

Please let me know if you need any additional information or if you have any suggestions on how to resolve this issue.

**Comment by kdhrubo** [comment]
Thanks for putting in so much details. I will look into this with priority and get this resolved.

**Comment by kdhrubo** [comment]
@tiger360 - would love to get in touch with you to discuss the project where you are using DB2Rest.

**Comment by kdhrubo** [comment]
@tiger360 - were you able to check? Is is working for you now?

**Comment by tiger360** [comment]
Sorry for the delay. I've been using this command line, but I'm still receiving the same message. Has the Docker image been updated?
`docker run -e DB_URL=jdbc:mysql://zeus-mysql:3306/ZeusEdu -e DB_USER=rooot -e DB_PASSWORD=147258369 kdhrubo/db2rest:latest`

**Comment by kdhrubo** [comment]
Yes it's updated
I believe you are using a cached image.

We are on discord for any assistance

**Comment by tiger360** [comment]
thanks it was the case .
it's running without the error now.
![image](https://github.com/kdhrubo/db2rest/assets/5794444/71bc23d9-1c3d-45ca-8e8c-4fdbe5186021)

**Comment by kdhrubo** [comment]
@tiger360 - awesome great to know. Do you mind sharing the use case where you are going to use DB2Rest?

Also do star the project as it helps to motivate us :)

**Comment by tiger360** [comment]
Yes, absolutely. It's designed for schools. We currently have a system in place that utilizes a MySQL database to manage the school's operations, and we're in the process of creating a REST API to aid in the development of a mobile app for students. However, despite no apparent errors, I'm still unable to access the Swagger UI via http://localhost:8080/swagger-ui/index.html.

**Comment by kdhrubo** [comment]
Will look into it ASAP

**Comment by kdhrubo** [comment]
The port mapping is not done hence traffic is not reaching db2rest running on docker. This is a defect in our documentation will fix that asap. Please add port mapping `-p 8080:8080` as shown below: 

`docker run -p 8080:8080 -e DB_URL=jdbc:mysql://zeus-mysql:3306/ZeusEdu -e DB_USER=rooot -e DB_PASSWORD=147258369 kdhrubo/db2rest:latest`

**Comment by kdhrubo** [comment]
As discussed on discord support channel, we will close the issue  now. Please open a new issue if you have problems or reach us on discord.
